version: '3.8'
services:
  avito-shop-service-test:
    build: .
    container_name: avito-shop-service-test
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shop"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - internal

  redis:
    image: redis:7
    container_name: redis-test
    command: redis-server --requirepass redis --bind 0.0.0.0
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  e2e-tests:
    image: golang:1.23
    container_name: e2e-tests
    working_dir: /app
    volumes:
      - ./:/app
    command: go test -v ./internal/services/e2e
    depends_on:
      avito-shop-service-test:
        condition: service_started
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata_test:
